- juser/user_api.py
> Ubuntu的passwd命令不支持--stdin选项，使用chpasswd替代，在CentOS上已经验证有效

- jperm/views.py
- juser/user_api.py
- juser/views.py
- templates/jasset/asset_add.html
- templates/jasset/asset_edit.html
- templates/juser/user_add.html
- templates/juser/user_edit.html
commit f60a8969268ddcab0e029fb9821b990f90113846
Author: ibuler <ibuler@qq.com>
Date:   Wed Feb 24 12:32:41 2016 +0800
modify(jasset) 统一管理用户文案
所有用得到管理用户文案的地，都进行了统一
更改了 管理用户使用默认的对齐
去掉了分隔线
commit b6fc8b777f20884f12ebe7d5d6714d42ebb88014
Author: ibuler <ibuler@qq.com>
Date:   Wed Feb 24 12:29:47 2016 +0800
change(juser) 修改用户添加流程
1. 添加新用户，不在为该用户设置密码
2. 强制用户使用key登陆跳板机，为了安全性
3. 更改邮件文案和不发送邮件提示文案
commit caefbdc9175cf21b4f5f803edfba7e2b4dc88fb1
Author: ibuler <ibuler@qq.com>
Date:   Wed Feb 24 11:34:33 2016 +0800
fix(juser) 推送系统用户，选择密钥时不为用户生成密码
当推送系统用户时，选择系统用户使用密钥时没有必要为系统用户生成密码，
以免造成安全上的问题,在代码上也属于冗余.
> 统一资产添加文案，修改添加用户流程，修复添加系统用户使用key推送，不生成密码

- jumpserver/views.py
- run_websocket.py
- templates/exec_cmd.html
- templates/jlog/log_online.html
- templates/jlog/web_terminal.html
1.修改run_websocket.py 使得其可以包含Django直接运行
其中修改部分URL代码，使得其适合修改后的代码
之后运行仅需要Python run_websocket.py 即可，manage.py 不需要运行了
2.修复log kill（阻断）功能
> 整合Tornado和Django，修复阻断功能

- run_websocket.py
- service.sh
用户IP获取修复
如果使用nginx
则会获取self.request.headers.get("X-Real-IP")，self.request.remote_ip的值为127.0.0.1
如果不使用nginx
self.request.headers.get("X-Real-IP")为null，self.request.remote_ip的值为正确的ip地址
注释了django runserver
> Ip get bug

- install/install.py
安装脚本的默认用户名设定是jumpserver，此处显示默认为root会导致安装失败
我就一路回车使用root安装，然后发现安装不成功
> 安装脚本默认数据库用户名

- jasset/asset_api.py
1. 超时原因应该是sshd　的配置引起的，当前bsd的更新　相对于其他发行版　慢，这个原因估计的bsd自身有关
2. 更新对freebsd 收集硬件信息的支持。 注意：ansible 的setup模块对于b sd获取的字段　越有偏差，而且无法获取硬盘信息，这个后期可以　提交patch 给ansible的setup模块。
close #80
> fix (jasset): 　修复连接超时，以及freebsd无法更新硬件信息

- juser/user_api.py
当用户已经登录到jumpserver时，web上删除用户时失败，也没有提示
修改方法: userdel -r -f 强制删除
close #156
> fix(userdel) 修复无法删除在线用户bug

- templates/jlog/web_terminal.html
经测试由于字体原因，可以安装Monaco字体解决，然而不太方便
添加第二字体为 微软雅黑，经测试解决
fixed
close #158
> fix(web terminal) Windows 浏览器使用chrome -换行

- jperm/models.py
- jperm/views.py
1. 修改password字段的长度，对称加密过后的字符串会变长，所有设置得比较大(512)
2. 修改后端检查密码长度，并触发异常。
> fix (jperm):   修复密码添加和更新 role时 密码过长引起的bug

- templates/jasset/group_edit.html
在主机组编辑页面，如果直接执行回车会导致主机组中主机信息丢失。
本修复方法是关闭回车提交
> 修复主机组编辑时回车导致主机丢失问题

- jlog/views.py
- `os.makedirs(name, mode=0o777, exist_ok=False)`  该方法在某些系统中传入的权限参数`mode`不生效 ;
> Replace os.makedirs to mkdir.

- juser/views.py
修改信息保存后数据不是最新的而是之前的数据，因为在object的惰性查询不会获取到最新的数据，因此需要在缓存的对象基础上修改save后commit到数据库。
> User object is not the user, must update at the user

- juser/views.py
存储在数据库的用户信息是使用Django框架的库提供的默认Hash算法pbkdf2_sha256，在登录后修改用户信息时使用的是Django的用户接口set_password(juser/views.py的change_info方法），但是在重置密码的reset_password方法中却使用了纯MD5（PyCrypt.md5_crypt）加密。
这个应该是一个Bug，但是不影响使用，查了下Django的django/contrib/auth/hashers.py中的identify_hasher方法，支持纯MD5和SHA1的（根据Hash结果串长度），所以修改了密码登录也是没有问题的。
> 修复通过重置密码链接重置密码的一个小Bug

- jperm/ansible_api.py
- jperm/views.py
当用户没有的role 已经没没有关联sudo 别名时，会删除该用户。
> 修复sudo别名取消后不回收bug

- apps/common/utils.py
在用户修改密码的邮件中的链接，如：http://10.99.1.4:8080/users/password/reset?token=b'eyJhb ... ... xNpQ' ， token=b'xxxx'，在解析时会当成一个整体的字符串处理而不是一个 bytes。
>>> token = b'xxxxx'
>>> url_token = '%s' % token
>>> url_token
"b'xxxxx'"
在 unsign_t 函数中处理时会传入一个类似 "b'xxxxx'" 的错误参数。
> change sign_t return from bytes to str.

- apps/common/templatetags/common_tags.py
start and end will be float when current_num >= 3 and display % 2 == 1, which will lead to `TypeError: 'float' object cannot be interpreted as an integer`
> fix bug in pagination_range function

- apps/assets/tasks.py
fix bug: variable i is not the host name, because summary['failed'] is something like [("hostname1", "error message 1"),("hostname1", "error message 1")]
> fix bug: variable i should be the host name

- apps/users/utils.py
目前的逻辑是用户每一次登陆coco都会更新token, 更新的函数过期时间是一个不可更改的值3600, 如果用户自定义的过期时间大于这个值的话, 就会出现{token: userid}这个cache早于{userid_remote_ip: token}这个cache过期, 导致用户可以获取token, 但是服务端根据token获取不到用户ID,就会出现报错Invalid token or cache refreshed, 生产环境遇到的问题.
> token过期bug

- apps/users/models/user.py
- apps/users/templates/users/user_profile.html
- bugfix: 解决用户失效时间为空时，无法使用密码进行ssh登录跳板机的问题。
- bugfix: 个人信息页面个人信息pannel错位。
```
AttributeError at /api/users/v1/auth/
'NoneType' object has no attribute 'strftime'
Request Method: POST
Request URL: http://127.0.0.1:8080/api/users/v1/auth/
Django Version: 1.11.4
Python Executable: /opt/py3/bin/python
Python Version: 3.6.1
Python Path: ['/data/deployment/jumpserver/apps', '/usr/local/lib/python36.zip', '/usr/local/lib/python3.6', '/usr/local/lib/python3.6/lib-dynload', '/opt/py3/lib/python3.6/site-packages', '/data/deployment/jumpserver', '/data/deployment/jumpserver/apps']
Server time: Wed, 30 Aug 2017 23:18:47 +0800
Installed Applications:
['users.apps.UsersConfig',
'assets.apps.AssetsConfig',
'perms.apps.PermsConfig',
'ops.apps.OpsConfig',
'audits.apps.AuditsConfig', …
```
> bugfix: 解决用户失效时间为空时，无法使用密码进行ssh登录跳板机的问题

- apps/ops/urls/api_urls.py
- apps/ops/urls/view_urls.py
ops模块缺少app_name，导致后面无法执行makemigrations
> [Bugfix] ops Add app_name

- apps/assets/views/asset.py
- apps/users/views/group.py
使终端管理的应用用户不显示在用户组里
修复导入资产列表IP字段前后有空格问题，导入资产列表时domain保存为对象
> 终端管理用户显示，资产导入IP字段空格，资产导入domain字段保存

- apps/assets/api/node.py
- apps/assets/models/node.py
- apps/assets/serializers/node.py
- apps/assets/templates/assets/_asset_list_modal.html
- apps/assets/templates/assets/asset_detail.html
- apps/assets/templates/assets/asset_list.html
- apps/users/templates/users/user_granted_asset.html
修复：资产树节点，
1. 取消model value unique，并添加唯一性校验，serializers/api中；
2. 修改新增节点计数器规则；
3. 修改资产树节点默认只展开root节点的直接子节点；
4. 修复从root节点移除资产：如果一个资产既属于root又属于其他节点，那么可以从root节点移除；
> 修复：资产树节点，取消model value unique，并添加唯一性校验，serializers/api中；修改新增节点计数器规则；

- apps/templates/_footer.html
引用写死了http协议, https的情况下会触发Mix Content的warning导致浏览器不信任.
此图片页面未发现有实际展示, 建议删除.
> remove useless image

- config_example.py
#1404  这位老兄指出了   BROKER_URL 未使用
搜索了 celery 库文件和jumpserver项目 确实只用了CELERY_BROKER_URL, 顺手提一个PR
> [Update]删除示例配置中未使用的BROKER_URL配置

- apps/ops/celery/utils.py
CrontabSchedule默认的时区是UTC,  调度会偏离预期,  需要在创建crontab任务时更新时区.
https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/models.py#L177
> [Bugfix] celery beat crontab task timezone issue

- apps/ops/celery/logger.py
debug模式有概率出现task日志打印完毕, 但是celery debug日志继续写入导致报错
ValueError : I/O operation on closed file.
> [Bugfix] operation on closed file.

- apps/assets/models/node.py
bugfix: node get_all_children逻辑
bug示例：
当前节点key为`0:1`,存在节点`key`为'0:10','0:11',...时，get_all_children也会将其匹配到
> [Bugfix] node get_all_children

- requirements/alpine_requirements.txt
add gcc libc-dev linux-headers make autoconf for pip install -r requirements
> add gcc libc-dev linux-headers make autoconf

- apps/assets/tasks.py
Some OS like SUSE12SP3 may not create group when create an OS user. In this case, the task "Set home dir permission" will always fail as the group doesn't exist in the system.
> Assure group when push system user to asset

- apps/authentication/backends/openid/models.py
Signed-off-by: YanzheL <lee.yanzhe@yanzhe.org>
当使用OpenID认证时，用户登录后的姓名`User.name`不会被自动设置，并且[会使用用户名作为默认的用户姓名](https://github.com/jumpserver/jumpserver/blob/master/apps/users/models/user.py#L536-L537)，这是一种不合适的做法，因为通常来说`name`和`username`的值是不同的。
因为OpenID的`UserInfo`会提供来自单点认证系统提供的用户姓名，所以应该把用户登录后的`name`设置为OpenID提供的`name`，这样前端界面就会显示正确用户姓名
> [Update]使用OpenID提供的UserInfo.name作为用户姓名

- requirements/requirements.txt
解决`1.11.5`版本无法在`alpine:3.11`容器镜像下通过pip安装的问题
`kombu==4.0.2`版本不兼容python3.7，详情请见[kombu issue](https://github.com/celery/kombu/issues/841)
需要4.2.0版本以上才支持python3.7
4.1.0版本不兼容python3.7，而4.1.1版本修复了这个问题
解决 #3670 所述的包版本依赖不兼容的问题
Fixes #3670
> [Update]修复部分pip包依赖的版本不兼容问题

- apps/authentication/backends/radius.py
* fix(radius): 修复radius认证失败问题，添加get_django_user方法参数（django-radius==1.4.0 中添加了额外参数）
* fix(radius): 修复radius认证失败问题，重写authenticate方法（django-radius 不接受public_key参数)
> fix(radius): 修复radius认证失败问题 (#4342)

- apps/assets/serializers/asset.py
复现：
`curl --request POST --url http://192.168.25.117:8080/api/v1/assets/assets/ --header 'Authorization: Bearer ioU8ikrPbH9EEH5TDYYx3UIlTmn0iYvqS2Nw' --header 'Content-Type: application/json' --data '{ "hostname": "test", "ip": "192.168.0.111", "admin_user": "024fcdcc-c18d-48ea-aeef-827f06e593ff", "admin_user_display": "root", "platform": "Linux", "nodes": [ "32d3d9eb-4b88-4e00-9cd1-31a222003844" ] }'`
页面显示为
协议组: s,s,h,/,2,2
@BaiJiangJie 
问题的描述：
在 apps/assets/models/asset.py 文件中：
后台Asset Model的protocols字段保存的类型和格式是: str('ssh/22 rdp/3389')，
所以默认的default=ssh/22是没问题的。
修改的建议：
在 apps/assets/serializers/asset.py 文件中：
查找 protocols = ProtocolsField(label=('Protocols'), required=False)
修改为 protocols = ProtocolsField(label=('Protocols'), required=False, default=['ssh/22'])
来解决。
dup: …
> fix：通过 api 添加资产，不写 protocols 时，默认值应该是列表

- apps/orgs/api.py
版本升级后，admin_user表中有历史数据，导致组织页面上无关联关系后，依旧无法删除的问题
> fix: 因为admin_user表中有历史数据，导致组织无法删除

- apps/authentication/backends/saml2/views.py
perf: SAML2属性映射去掉域名前缀，用户反馈带着域名前缀，使用不太方便
> perf: SAML2属性映射去掉域名前缀

- apps/jumpserver/settings/libs.py
fix: 修复部署JumpServer在没有密码的redis上时，站内信数量不更新问题
> fix: 修复部署JumpServer在没有密码的redis上时，站内信数量不更新问题

- apps/authentication/backends/oidc/backends.py
Fix bug: oidc client token_endpoint_auth_method
https://github.com/jumpserver/jumpserver/issues/8165
Remove client_id and client_secret in request OIDC token endpoint payload.
> Fix oidc (#8165)

- apps/authentication/backends/saml2/views.py
Fixes issue #8287
Dumbly fixes redirect an empty URLs when the IDP sends blank RelayStates.
This fix was verified on two different Jumpservers.
> Fix issue #8287 with blank SAML's RelayState

- apps/audits/migrations/0021_auto_20230207_0857.py
fix: 解决JobLog表依赖顺序不对，导致从新迁移失败问题
> fix: 解决JobLog表依赖顺序不对，导致从新迁移失败问题

- apps/settings/api/email.py
> perf: 邮箱测试时，不填写'主题前缀'会报错

- apps/ops/ansible/inventory.py
测试资产可连接性选择账号的策略privileged_first如下进行匹配，
1、优先选择特权用户中和account_prefer匹配的
2、选择特权用户的第一个
3、选择普通用户中和account_prefer匹配的
4、选择普通用户的第一个
5、没找到
例如有如下账户
root(非特权)、test(特权) 选择 -> test
root(非特权)、test(非特权) 选择 -> root
root(特权)、test(特权) 选择 -> root
解决SQLServer中特权用户名称为sa，且用户中存在root用户时，会使用root用户去测试资产可连接性
> perf: 测试资产可连接性选择账号策略优化

- apps/common/drf/parsers/base.py
Fix SyntaxWarning
fix: SyntaxWarning, apps/common/drf/parsers/base.py:114, "is" should be "=="
- [✓] Made sure tests are passing and test coverage is added if needed.
- [✓ ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ✓] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.
> fix: SyntaxWarning, apps/common/drf/parsers/base.py:114, "is" should be "=="

- apps/ops/notifications.py
AttributeError: type object 'Status' has no attribute 'get_terminal_latest_stat'
fix AttributeError
change import module name to below
from terminal.models.component.status import Status
from terminal.models import Terminal
- [✓] Made sure tests are passing and test coverage is added if needed.
- [✓] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [✓] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.
> fix: type object 'Status' has no attribute 'get_terminal_latest_stat'

- apps/audits/handler.py
fix: 解决migrate文件中迁移数据会触发信号导致字段不对应错误引发迁移失败问题
> fix: 解决migrate文件中迁移数据会触发信号导致字段不对应错误引发迁移失败问题

- apps/common/serializers/dynamic.py
This PR aims at solving a latent bug when `filed_type` belongs to `int`, `bool` and `list`. This bug will cause errors when someone choose to deploy customized/official jumpserver from code.
The `serializers.IntegerField`, `serializers.ListField`, and `serializers.BooleanField` don't pop the argument named `allow_blank` out and the `Field` class they inherit don't accept such an argument, so that this argument should be pop out when `field_type` is `int`, `bool`, `list`. Thus, I add two lines of codes to pop `allow_blank` when `field_type` exists in `data` and belongs to the type of `int`, `bool`, `list`, to avoid this error.
Details of `Field`, `IntegerField`, `ListField`, `BooleanField` can be refer to https://github.com/encode/django-rest-framework/blob/3.13.1/rest_framework/fields.py
> fix a latent bug when field_type belongs to int, bool and list.

- apps/common/sdk/im/feishu/__init__.py
> fix: 修复飞书markdown信息渲染问题

- apps/assets/utils/k8s.py
Kubernetes apiserver endpoint 可能为默认的443端口，而会被忽略，例如腾讯云TKE `https://cls-xxxxxxx.ccs.tencent-cloud.com`
通过网域连接kubernetes资产时，建立ssh隧道时需要提供远端的端口号，`urlparse`库在端口省略时返回`None`，导致报错`PORT is not a number`
kubernetes endpoint必然为https协议，设置默认端口为443
> perf: 通过网域连接k8s时支持默认端口

- apps/jumpserver/settings/base.py
SERVER_NAME兼容以下三种情况
- SERVER_NAME="demo.jumpserver.org"
- SERVER_NAME="demo.jumpserver.org jms.jumpserver.org"
- SERVER_NAME="demo.jumpserver.org,jms.jumpserver.org"
> perf: 兼容SERVER_NAME值多种情况

- pyproject.toml
修复SAML2认证回调/core/auth/saml2/callback/时偶发出现http 502错误
Keycloak认证成功回调jumpserver的接口/core/auth/saml2/callback/时会响应SAMLResponse，响应数据为XML格式
下图为gunicorn.log中记录的日志，在收到saml response后，worker异常退出，并重启worker
此时nginx返回502并记录了错误日志
参考：https://github.com/SAML-Toolkits/python3-saml/issues/396
> 指定lxml版本为4.9.3

- apps/assets/automations/gather_facts/host/windows/main.yml
解决windows主机硬件信息在列表展示时不显示问题：
* windows主机获取硬件信息后cpu信息记录字段不全，导致列表显示硬件信息时windows主机整个字段都显示不出来
* windows主机获取硬件信息后内存单位与posix主机单位不一致，列表显示出来后内存大小单位错误
> fix: Ensure memory units for Windows host hardware information are consistent with other hosts; align CPU information fields with other hosts.

- apps/assets/automations/gather_facts/host/posix/main.yml
多个不同路径挂载相同硬盘时现在的统计方式也会导致多次计入硬盘大小。
调整后只按设备口径计算非可插拔的(u盘等removable为'0')、关联物理设备的(逻辑卷等设备host为'')大小，避免重复计算，也不计入nfs等挂载大小，更符合实际主机硬盘大小。
同时，也避免目前硬盘大小计算时，如有docker直接向容器内挂载nfs等场景会ansible取不到size_total，导致整个硬件信息都获取失败的情况
```
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'size_total'.
```
> fix: 主机硬件信息硬盘大小避免多次挂载重复计入

- apps/templates/_copyright.html
企业版登录进行 MFA 二次认证时，无法隐藏页脚的 “Copyright FIT2CLOUD 飞致云 © 2014-2024“ 内容
> perf: Enterprise Edition Hide Footer Copyright Content

- apps/common/utils/common.py
- apps/common/utils/http.py
the X-Forwarded-For header is not formally standardized, some variations to the IP address format exist. For example, some implementations include the port number of clients
```
X-Forwarded-For: 203.0.113.195:41237, 198.51.100.100:38523
```
Fix the abnormal issue of client IP acquisition when implementing X-Forwarded-For non-standard methods
> fix: 修复非标准实现 X-Forwarded-For 时的问题

- apps/jumpserver/routing.py
When using the ```ws://jumpserver.com/ws/ops/tasks/log/``` api, if an Authorization Header is passed into the api, the websocket connection will fail.
An error will happen when calling the authentication method in SignatureAuthentication, the authentication method in AccessTokenAuthentication will not be executed, and ultimately the authentication will fail.
> fix: fixed the issue that websocket cannot use "Authorization" header

- apps/assets/models/zone.py
- apps/assets/pagination.py
- apps/assets/tasks/utils.py
- apps/authentication/mixins.py
- apps/common/cache.py
- apps/common/sdk/im/wecom/__init__.py
- apps/ops/signal_handlers.py
- apps/ops/ws.py
- apps/perms/pagination.py
- apps/terminal/backends/__init__.py
This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> Resolve warnings of logger library

- apps/audits/backends/es.py
- apps/common/plugins/es.py
- apps/terminal/backends/command/es.py
命令记录ES 搜索，指定字段完全匹配优化为模糊匹配，与数据库搜索对齐
数据库搜索效果如下（按字段模糊匹配）：
> perf: ES command log supports fuzzy search

- apps/terminal/applets/dbeaver/app.py
- apps/terminal/applets/dbeaver/config/drivers.xml
- apps/terminal/applets/dbeaver/manifest.yml
优化远程应用 dbeaver 驱动配置，指向公共目录驱动，避免驱动文件多次复制到用户目录占用发布机磁盘空间
> perf: dbeaver uses a fixed driver directory
