jumpserver/jumpserver

connect.py
=> 修复当用户使用Ctrl+C结束进程时,没有正确退出

jperm/views.py, juser/views.py
As a normal user, I can not see my own login logs due to login logs not filted by username but by name.
=> fix user can not get login logs bug

connect.py
0.0000000000000000000000000001
=> exact match

connect.py, templates/jlog/log_online.html
=> bugfix：connect.py log_online.html

connect.py
=> add choose group to execute commands.

connect.py
=> fix remote ip bug

install/install.py, juser/views.py
当有用户uuid 或账号姓名电邮地址信息时，可以修改任意账号的密码
=> 当有用户uuid 或账号姓名电邮地址信息时，可以修改任意账号的密码

jumpserver/views.py, templates/exec_cmd.html, templates/jlog/web_terminal.html
=> fix wss issue when using https  #37

connect.py
=> Get SSH client IP address from environment

jlog/views.py, templates/jlog/log_online.html
* SSL support for realtime monitor
* term.js call problem
=> Fix Realtime Monitor Issue

install/install.py
添加数据库自启动服务。修复服务器重启后./server.sh start 会提示错误——“Starting jumpsever
service:run_websocket.py not running”
=> 添加本地mysqld自启动服务

juser/views.py, templates/juser/user_list.html
修改当普通用户下载sshkey后将私钥删除，管理员账户不受限
添加当不存在key时直接生成key的按钮
=> V3.0 beta issue 62

connect.py
commit 47ce09393c59300f5b97f7b2b7de390c044fca86
Author: ibuler <ibuler@qq.com>
Date:   Thu Feb 25 18:34:46 2016 +0800
fix(connect.py) 用户禁用后仍可ssh登陆jumpserver
修改connect.py添加判断
资产禁用还没有考虑，改动太大，留后续版本更改
ref https://github.com/jumpserver/jumpserver/issues/83
=> 修复用户禁用后仍可ssh登陆跳板机

functions, install/install.py, install/next.py, jperm/ansible_api.py, jperm/views.py, service.sh
1. 修复 #77 回收系统用户为回收相关sudo配置问题。
2. 修复 #50 修复install.py 可以兼容 ubuntu的安装。
=> install.py兼容 ubuntu 和 回收资源时，回收sudo配置

jumpserver.conf, jumpserver/settings.py, run_websocket.py
=> fix: ip and port use jumpserver.conf to configure

install/install.py, install/next.py, jperm/ansible_api.py
1. Ubuntu14.04/15.10
2. Debian 7.8/8.2
3.Cenos6/7
4.Fedora23
=> install.py兼容 多个平台

jlog/log_api.py, jumpserver/settings.py
1. 修改日志参数
2. 修改处理间隔，每10分钟处理一次
3. 修改处理策略
ssh: 1小时不操作，就kill掉
web: 超过1天，就设置完成
=> hot_fix(kill invalid connection) 紧急修复超时异常连接

run_server.py
=> fix(run_server.py) 修改一个常规错误，函数参数个数

templates/jlog/web_terminal.html
=> fix(web teminal): 修改动态改变窗口大小bug

install/install.py, service.sh
1. 处理lockfile 目录不存在问题
2.依赖安装失败后，提醒用户。
=> 修复一些install.py 中的小问题

jlog/views.py, templates/foot_script.html, templates/jlog/log_online.html
=> fix(ws protocal): 修复所有ws自动获取

install/install.py, jumpserver.conf, jumpserver/settings.py, jumpserver/views.py
上次修改已可以自动获取 ws地址，去掉无用设置和配置文件指定
去掉install.py中的设置
=> change(with pre fix) 修改安装和jumpserver.conf

templates/index.html
=> fix(bug) 修复首页点击头像404问题

connect.py
=> pull issue #120

templates/jlog/log_online.html
=> fix: when moniter the terminal, fix the shake

jasset/asset_api.py
fix(asset) 修复批量上传的bug
修复上传excel导致的上传失败，如果密码为int，python excel会转换为float类型，对称加密模块会加密失败
此bug比较难发现...
close #issuenum
=> fix asset upload bug

run_server.py
=> no command data

install/requirements.txt
=> change(install.py) 增加pyte库

run_server.py
=> fix: command recoder bug fix

juser/user_api.py, juser/views.py
=> fix(user edit) 修改用户导致密码问题

templates/exec_cmd.html, templates/jlog/log_online.html
=> change(font) 修改使用websocket的页面字体,增加监控size

templates/footer.html
=> change(version num) change jumpserver version

jlog/views.py
=> fix(log) fix load_full_log function bug

templates/jasset/asset_cu_list.html, templates/jasset/asset_list.html
=> fix(web terminal) 修改web terminal初始窗口大小

install/install.py, install/requirements.txt
=> fix(connect) 修复paramiko连接速度特么慢问题

connect.py
之前只是输入id登陆，增加了模糊搜索登陆
如果搜索唯一则登陆
=> fix(connect) 增加模糊搜索

connect.py
=> new feature (connect) Ignore case in searching

jlog/views.py, run_server.py, static/js/record.js, static/js/webterminal.js, templates/jasset/asset_list.html, templates/jlog/log_online.html, templates/jlog/web_terminal.html
添加手动resize窗口按钮，默认terminal窗口大小为100列x35行，当手动修改窗口行列大小时，下次打开窗口时会记录之前窗口大小
=> Window resize

jumpserver/views.py
紧急修复下载文件后静态文件404问题
忽略下面的“紧急修复监控白屏问题”（git commit的记忆功能。。。）
=> Static bug

jlog/views.py
=> fix bug index out of range

jasset/models.py, jasset/views.py, jumpserver/models.py, jumpserver/views.py, templates/jasset/asset_add.html, templates/jasset/asset_edit.html, templates/setting.html
1. 主要修复setting里面 密码输入时提示错误，已经setting时密码长度问题
2. 修复资产用户名和密码长度问题
3. 修复资产edit时 异常无法返回问题
=> Bug fix hostname

install/install.py, jasset/models.py, jasset/views.py, jlog/views.py, jumpserver/models.py, jumpserver/views.py, static/js/webterminal.js, templates/jasset/asset_add.html, templates/jasset/asset_edit.html, templates/jasset/asset_list.html, templates/jlog/web_terminal.html, templates/setting.html
=> Merge with master

connect.py, jperm/views.py
=> 修复cli 端资产列表显示

connect.py
=> fix passwd input

connect.py
=> 修复vim等交互式命令引起的记录命令bug

templates/juser/group_add.html
=> users_selected keep new

install/docker/run.sh
```bash
docker run -v "/DATA_DIR:/data" jumpserver
```
挂载data目录到docker里面去的时候，**/data/logs**可能不存在，自动创建这个目录。
=> make sure logs directory exists

apps/common/utils.py
=> [Bugfix] 修复管理用户上传私钥兼容问题

apps/assets/models/user.py, apps/templates/_user_profile.html
https://github.com/jumpserver/jumpserver/issues/443
=> fix left's users logout

Dockerfile-py3
=> Dockerfile 优化

apps/assets/models/asset.py, apps/locale/zh/LC_MESSAGES/django.po
platform  field didn't support i18n.
=> Support i18n for asset `platform` field

apps/jumpserver/settings.py
=> 修改redis有密码连接失败问题

apps/assets/views/asset.py, requirements/requirements.txt
1. auto detect the encoding of csv
2. if id in csv is empty, let it equal 0
3. if hostname exists, give up this asset
=> Fix importing csv bugs

apps/static/css/style.css
=> 修改调用地址，解决前端页面打开慢的问题

apps/applications/api.py, apps/users/utils.py, apps/users/views/login.py
1、 login_ip 使用 X-Real-IP 记录
2、X-Real-IP 在 django 中对应为 HTTP_X_REAL_IP
=> x-real-ip 对应 HTTP_X_REAL_IP, login_ip 使用 X-Real-IP

docs/project_structure.md
=> [Bugfix] 修改项目结构描述

requirements/deb_requirements.txt
=> ubuntu16.04 deb_requirements.txt update

apps/assets/tasks.py, apps/common/validators.py, apps/perms/serializers.py
* [Update] 修改版本号
* [Update] 默认关闭定时任务
* [Update] 修改授权列表创建api，返回id
* [Update] 修改用户名校验规则
=> Perms return (#1293)

docs/faq.rst, docs/setup_by_centos7.rst
=> [Update]修改文档

utils/make_migrations.sh
=> 更新make_migrations.sh的migration逻辑

docs/step_by_step.rst
update docker-guacamole version  to latest
=> update docker-guacamole version  to latest

apps/assets/templates/assets/admin_user_list.html, apps/assets/templates/assets/domain_list.html, apps/static/js/jumpserver.js
=> [Update]修改提示文字

README.md, utils/make_migrations.sh
=> [Update]修改url地址

docs/faq.rst, docs/faq_telnet.rst
=> [add]增加telnet文档

apps/perms/api.py, apps/perms/templates/perms/asset_permission_list.html
Reverts jumpserver/jumpserver#1515
=> Revert "授权页面分页问题"

docs/user_api.rst
=> [Add]更新api手动调用文档

apps/users/utils.py
=> [Update]替换淘宝IP查询接口

docs/distributed_02.rst, docs/faq.rst
=> [Update]更新文档

docs/distributed_02.rst, docs/distributed_04.rst, docs/faq.rst, docs/setup_by_centos7.rst, docs/setup_by_ubuntu.rst, docs/step_by_step.rst
修正nginx代理参数，使jumpserver能获取到正确的ip；
=> [Fix]修正nginx代理参数

docs/faq.rst
=> [Update]增加FAQ文档内容

docs/faq.rst, docs/faq_ldap.rst
=> [Add]增加ldap文档

docs/faq.rst
=> [Fix]修正多余字节

docs/upgrade.rst
=> [Update]修改升级文档

docs/distributed_01.rst, docs/distributed_03.rst, docs/distributed_04.rst, docs/distributed_05.rst
=> [Fix]修改分布式部署文档

docs/start_automatically.rst
=> [Update]更新

docs/distributed_06.rst, docs/distributed_07.rst, docs/dockerinstall.rst, docs/faq_docker.rst, docs/faq_rdp.rst, docs/faq_ssh.rst, docs/setup_by_centos7.rst, docs/upgrade.rst, docs/user_api.rst
=> [Update]Docs

apps/common/models.py, apps/common/tree.py
* [Update] 修改心跳偶人时间
* [Update] 修改Node比较
* [Bugfix] 修复bug
=> Bugfix (#2252)

apps/locale/zh/LC_MESSAGES/django.po, apps/ops/templates/ops/command_execution_create.html, apps/users/models/user.py, apps/users/templates/users/user_detail.html, apps/users/templates/users/user_profile.html, apps/users/templates/users/user_update.html, apps/users/views/login.py, apps/users/views/user.py
* [Update] 禁用其他认证方式修改密码
* [Update] 禁用其他认证方式修改密码
* [Update] 禁用其他认证方式修改密码
=> [Update] 禁用其他认证方式修改密码 (#2286)

apps/assets/templates/assets/asset_detail.html, apps/audits/templates/audits/operate_log_list.html, apps/authentication/templates/authentication/login_otp.html, apps/users/templates/users/reset_password.html
* [Update] 修复小问题
* [Bugfix] 修复操作日志动作、资源类型过滤不成功的bug
=> [Update] 修复小问题 (#2557)

Dockerfile, apps/templates/_user_profile.html, requirements/rpm_requirements.txt
* [Update] 修改Logo 的位置
* [Update] 修改镜像build
=> Bugfix (#2569)

apps/settings/serializers.py
[issue 2577](https://github.com/jumpserver/jumpserver/issues/2577)
=> 允许配置email密码为空

apps/assets/serializers/asset.py, apps/assets/serializers/base.py, apps/assets/templates/assets/asset_create.html, apps/perms/utils/asset_permission.py
* [Update] 解决授权资产显示禁用资产的问题
* [Bugfix] 解决资产更新页面取消激活失败的问题
* [Bugfix] 解决资产详情页面禁用资产时会清除协议的问题
* [Bugfix] 解决创建/更新管理用户、系统用户提交密钥错误时报错的问题
=> [Update] 解决授权资产显示禁用资产的问题 (#2975)

apps/assets/templates/assets/admin_user_create_update.html, apps/assets/templates/assets/asset_list.html, apps/assets/templates/assets/system_user_list.html, apps/jumpserver/views.py, apps/perms/api/mixin.py, apps/perms/api/user_permission.py, apps/templates/_header_bar.html, apps/users/templates/users/_granted_assets.html, apps/users/templates/users/user_list.html
* [Update] 修改排序，去掉标签
* [Update] 修改批量更新后刷新页面
* [Update] 修改面包屑
* [Update] 修改用户排序
* [Update] 处理未登录主机显示为负数
* [Update] 支持单个资产的搜索
=> Bugfix (#2980)

apps/assets/templates/assets/_asset_user_list.html, apps/assets/templates/assets/asset_list.html, apps/ops/templates/ops/adhoc_history.html, apps/ops/templates/ops/task_adhoc.html, apps/ops/templates/ops/task_history.html, apps/perms/migrations/0002_auto_20171228_0025_squashed_0009_auto_20180903_1132.py, apps/static/js/jumpserver.js, apps/templates/_foot_js.html, apps/terminal/templates/terminal/command_list.html, apps/terminal/templates/terminal/session_list.html
* [Bugfix] 修复英文时间时期的bug
* [bugfix] 修复session时间日期的问题
* [Bugfix] 修改时间日志格式化错误
* [Update] 修改函数名称
* [Update] 修改函数顺序
* [Update] 注释部分迁移文件内容
=> Bugfix (#3007)

apps/assets/templates/assets/_node_tree.html, apps/users/templates/users/_granted_assets.html, apps/users/templates/users/user_granted_asset.html
* [Bugfix] 修复英文时间时期的bug
* [bugfix] 修复session时间日期的问题
* [Bugfix] 修改时间日志格式化错误
* [Update] 修改函数名称
* [Update] 修改函数顺序
* [Bugfix] 修复节点刷新菜单一直append的bug
=> Bugfix (#3014)

.dockerignore, .gitignore, Vagrantfile
https://anjia0532.github.io/2019/07/24/jumpserver-vagrant-virtualbox
=> added Vagrantfile to support windows dev

apps/applications/templates/applications/user_remote_app_list.html, apps/assets/templates/assets/user_asset_list.html, apps/assets/utils.py, apps/orgs/views.py, apps/perms/utils/asset_permission.py
* [Update] 用户资产页面链接是 新窗口打开
* [Bugfix] 修复切换组织时， refer为空导致的bug
* [Update] 修复执行命令时报错
=> Bugfix (#3284)

apps/assets/backends/manager.py, apps/assets/models/authbook.py
1. 创建AuthBook对象的create方法从ModelManager中移动到Model中，保留原生的对象create方法；
2. 同时添加事务处理；
=> [Update] 优化创建AuthBook对象

apps/authentication/errors.py, apps/authentication/views/login.py, apps/authentication/views/mfa.py
修复 /auth/login/otp/ 直接登录或者其他问题引起的SessionEmpty 错误，
当引发该问题时，转到登录页面
=> Fix otp error

.github/release-config.yml, .github/workflows/release-drafter.yml
- 修改使用action jumpserver/action-build-upload-assets
=> ci(build): 修改 workflow

utils/build.sh
=> ci(build): 修改 构建脚本

apps/assets/models/authbook.py
修改创建AuthBook对象锁机制，解决并发操作堵塞问题，使用select_for_update替换redis_lock
=> fix(asset_user): 修改创建AuthBook对象锁机制，使用select_for_update替换redis_lock

.github/workflows/jms-generic-action-handler.yml
=> ci(github): 添加通用action

apps/ops/celery/utils.py, apps/ops/tasks.py
feat(ops): 添加获取celery定时任务的函数<br>feat(ops): 项目启动时，清除指定的celery定时任务
=> feat(ops): 项目启动时，清除指定的celery定时任务;添加获取celery定时任务的函数

apps/audits/models.py
=> fix(OperateLog): 修复操作日志按时间查询慢

apps/common/fields/model.py, apps/common/utils/crypto.py
AES ECB加密模式是语义上不安全的。因此不应该再使用AES ECB模式加密私密信息。参考链接：
- https://crypto.stackexchange.com/a/20946
- https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)
- https://pycryptodome.readthedocs.io/en/latest/src/cipher/classic.html#ecb-mode
于是我添加了AES GCM模式为默认的加密解密方式，并保持与之前的加密解密方法兼容。
- 对于新的请求（如上传系统用户私钥等），将使用AES GCM模式加密解密用户的私密信息。
- 对于之前使用AES ECB模式加密的数据。将会先尝试使用AES GCM模式解密。解密失败则使用AES EBC模式解密。这样就可以与之前的方法兼容。
=> feat: 添加AES GCM模式为默认的加密方式

apps/assets/tasks/push_system_user.py
MESSAGE
AttributeError: 'UUID' object has no attribute 'name'
EXCEPTION(most recent call first)
AttributeError: 'UUID' object has no attribute 'name'
File "celery/app/trace.py", line 385, in trace_task
R = retval = fun(*args, **kwargs)
File "celery/app/trace.py", line 650, in __protected_call__
return self.run(*args, **kwargs)
File "assets/tasks/push_system_user.py", line 244, in push_system_user_to_assets
task_name = _("Push system users to assets: {}").format(system_user.name)
=> modify: AttributeError: 'UUID' object has no attribute 'name'

apps/common/db/utils.py
自动推送系统用户 task，格式化数组时因 asset id 是 uuid 导致格式化出错
=> fix:资产自动推送UUIDD数组格式化字符串失败

apps/assets/models/node.py, apps/assets/tasks/nodes_amount.py, apps/common/permissions.py, apps/orgs/api.py, apps/orgs/mixins/models.py, apps/users/models/user.py
perf: 优化OrgModelMixin save; org_root获取; org_roles获取; UserCanUseCurrentOrg权限类
=> perf(orgs): 优化(默认组织改为实体组织，并支持全局组织)

apps/jumpserver/conf.py, apps/settings/serializers/other.py
feat: 支持管理员配置导航栏上帮助中的url, 开源版本有跳转到企业版的链接
=> feat: 支持管理员配置导航栏上帮助中的url

apps/authentication/backends/saml2/views.py
=> feat: saml2认证支持https协议部署方式

requirements/requirements.txt
feat: 添加数据库SQLServer改密功能的python依赖库
=> feat: 添加数据库SQLServer改密功能的python依赖库

apps/authentication/backends/saml2/views.py
perf: 兼容不同版本间JumpServer获取的SAML2协议用户属性
=> perf: 兼容不同版本间JumpServer获取的SAML2协议用户属性

apps/settings/api/settings.py
=> fix: 修复setting perm

apps/locale/zh/LC_MESSAGES/django.mo, apps/locale/zh/LC_MESSAGES/django.po, requirements/requirements.txt
=> feat: 支持纳管百度云资产

apps/common/cache.py, apps/common/utils/connection.py, apps/common/utils/lock.py, apps/jumpserver/rewriting/session.py, apps/jumpserver/settings/base.py, apps/jumpserver/settings/libs.py, utils/start_celery_beat.py
feat: JumpServer支持部署在使用了ssl的redis上
=> feat: JumpServer支持部署在使用了ssl的redis上

apps/locale/ja/LC_MESSAGES/django.mo, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.mo, apps/locale/zh/LC_MESSAGES/django.po, apps/settings/serializers/auth/cas.py, apps/settings/serializers/terminal.py
=> perf: 优化各种翻译

apps/common/cache.py, apps/jumpserver/settings/libs.py
=> perf: 优化部分云厂商的redis连接的问题

apps/authentication/backends/saml2/views.py
feat: 优化SAML2生成的metadata文件内容及属性映射
=> feat: 优化SAML2生成的metadata文件内容及属性映射

apps/authentication/views/dingtalk.py, apps/authentication/views/mixins.py, apps/authentication/views/wecom.py, apps/jumpserver/urls.py, apps/locale/ja/LC_MESSAGES/django.mo, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.mo, apps/locale/zh/LC_MESSAGES/django.po, apps/templates/_base_double_screen.html, apps/tickets/notifications.py, apps/tickets/templates/tickets/_msg_ticket.html, apps/tickets/templates/tickets/approve_check_password.html, apps/tickets/urls/view_urls.py, apps/tickets/views/__init__.py, apps/tickets/views/approve.py
=> feat: 支持企业微信、钉钉直接审批工单

apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po, apps/templates/_base_double_screen.html, apps/tickets/templates/tickets/approve_check_password.html, apps/tickets/views/approve.py
=> perf: 企业微信、钉钉工单审批增加拒绝功能

apps/common/utils/connection.py, apps/jumpserver/rewriting/session.py, apps/jumpserver/settings/base.py, apps/jumpserver/settings/libs.py
perf: 兼容AWS上redis[ssl]无证书无法部署的问题
=> perf: 兼容AWS上redis[ssl]无证书无法部署的问题

requirements/requirements.txt
=> Updating redis version

apps/locale/ja/LC_MESSAGES/django.mo, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.mo, apps/locale/zh/LC_MESSAGES/django.po, apps/perms/templates/perms/_msg_item_permissions_expire.html, apps/perms/templates/perms/_msg_permed_items_expire.html
=> fix: 授权过期消息提示

utils/start_celery_beat.py
https://www.cnblogs.com/ghgyj/p/4047202.html
=> fix: 修复部署在无证书的Redis上，定时任务不执行的问题-v2.23

utils/start_celery_beat.py
fix: 修复部署在无证书的Redis上，定时任务不执行的问题-v2.21
=> fix: 修复部署在无证书的Redis上，定时任务不执行的问题-v2.21

utils/start_celery_beat.py
fix: 修复部署在无证书的Redis上，定时任务不执行的问题-v2.22
=> fix: 修复部署在无证书的Redis上，定时任务不执行的问题-v2.22

requirements/requirements.txt
=> perf: 更新oracle依赖包

README.md
=> perf: update readme

apps/common/sdk/sms/cmpp2.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po, apps/settings/api/sms.py, apps/settings/serializers/auth/sms.py
=> perf: 补充cmpp2翻译及部分报错提示

apps/authentication/templates/authentication/login_wait_confirm.html, apps/static/js/jumpserver.js
Reverts jumpserver/jumpserver#8777
=> Revert "fix: 修复服务端渲染请求缺少csrf token 问题"

apps/common/sdk/sms/endpoint.py, apps/common/sdk/sms/huawei.py, apps/jumpserver/conf.py, apps/settings/api/settings.py, apps/settings/api/sms.py, apps/settings/serializers/auth/sms.py
=> feat: 支持MFA可配置华为云平台短信对接

requirements/requirements.txt
=> feat: 改密计划支持MongoDB改密

apps/applications/serializers/attrs/application_category/db.py
=> perf: 修改数据库应用ssl相关字段名

apps/common/utils/file.py
feat: 支持对开启SSL/TLS的MongoDb数据库改密
=> feat: 支持对开启SSL/TLS的MongoDb数据库改密

apps/common/sdk/gm/piico/cipher.py, apps/common/utils/crypto.py
=> fix: 修复空字符串加密报错的问题

README.md
=> docs: 去掉 README 中表达有歧义的文字

README.md
=> docs: Change README description

apps/jumpserver/settings/base.py, apps/jumpserver/settings/libs.py, utils/start_celery_beat.py
=> feat: 支持部署在Redis哨兵集群上

apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po
=> feat: 云同步支持金山云

requirements/requirements.txt
=> feat: 支持网域网关应用改密-增加依赖

apps/applications/const.py, apps/applications/serializers/attrs/application_type/__init__.py, apps/applications/serializers/attrs/application_type/clickhouse.py, apps/applications/serializers/attrs/attrs.py, apps/assets/models/user.py, apps/terminal/models/session.py
feat: 支持纳管 clickhouse[Web Terminal]
=> feat: 支持纳管 clickhouse[Web Terminal]

apps/jumpserver/conf.py
=> perf: 增加一下配置的默认项

apps/applications/serializers/attrs/application_type/chrome.py, apps/audits/const.py, apps/audits/utils.py, apps/common/drf/fields.py
perf: 补充资产账号的操作日志记录
perf: 远程应用中的密码脱敏记录到操作日志中
perf: 优化个人信息部分操作日志内容
=> perf: 优化操作日志一些内容

apps/authentication/api/password.py, apps/authentication/forms.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po, apps/users/templates/users/forgot_password.html, apps/users/views/profile/reset.py
perf: 优化忘记密码，用户无手机号时无法使用手机号重置密码
=> perf: 优化忘记密码，用户无手机号时无法使用手机号重置密码

apps/applications/serializers/attrs/application_type/clickhouse.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po
=> perf: 增加clickhouse端口帮助文案及注释

apps/tickets/api/ticket.py, apps/tickets/serializers/ticket/ticket.py
feat: 支持具有超级工单权限的用户申请工单可以指定申请人，无权限的默认为当前登录用户
=> feat: 支持具有超级工单权限的用户申请工单可以指定申请人，无权限的默认为当前登录用户

apps/terminal/startup.py
fix: Redis哨兵切换时导致core和celery组件监听线程异常退出
=> fix: Redis哨兵切换时导致core和celery组件监听线程异常退出

apps/jumpserver/conf.py, apps/jumpserver/settings/base.py, apps/jumpserver/settings/libs.py, utils/start_celery_beat.py
perf: 支持sentinel开启ssl(Sentinel和Redis公用一套证书，无额外增加配置项)
=> perf: 支持sentinel开启ssl(Sentinel和Redis公用一套证书，无额外增加配置项)

apps/jumpserver/conf.py, apps/jumpserver/settings/base.py
perf: 增加DB_USE_SSL配置和redis配置统一
=> perf: 增加DB_USE_SSL配置和redis配置统一

apps/assets/const/database.py, apps/assets/const/protocol.py, apps/terminal/const.py
=> feat: 增加clickhouse

requirements/requirements.txt
=> perf: 清理无用的依赖包

apps/jumpserver/settings/base.py
=> perf: 优化Sentinels配置参数

apps/terminal/applets/navicat/setup.yml
=> fix: 修改navicat启动程序MD5值

apps/assets/serializers/asset/database.py
=> feat: Redis/MongoDB 支持SSL 

apps/terminal/applets/navicat/app.py
=> feat: 远程应用navicat支持试用版连接

apps/authentication/serializers/connect_token_secret.py, apps/terminal/applets/navicat/app.py
=> perf: navicat dba账号登录

apps/terminal/applets/navicat/app.py, apps/terminal/applets/navicat/main.py
=> feat: 保证认证信息一定清理

requirements/requirements.txt
Reverts jumpserver/jumpserver#9173
=> Revert "chore(deps): bump certifi from 2018.1.18 to 2022.12.7 in /requirements"

requirements/requirements.txt
fix: channels-redis版本回退导致redis哨兵ws连接有问题
=> fix: channels-redis版本回退导致redis哨兵ws连接有问题

apps/terminal/api/applet/applet.py, apps/terminal/serializers/applet.py
=> perf: 优化远程应用界面

README.md
=> chore(docs): README 进一步简化和优化

apps/accounts/automations/change_secret/database/mongodb/main.yml, apps/accounts/automations/change_secret/manager.py, apps/accounts/automations/gather_accounts/database/mongodb/main.yml, apps/accounts/automations/verify_account/database/mongodb/main.yml, apps/assets/automations/base/manager.py, apps/assets/automations/gather_facts/database/mongodb/main.yml, apps/assets/automations/ping/database/mongodb/main.yml, apps/ops/ansible/inventory.py
=> feat: 测试可连接性mongodb支持ssl

apps/common/management/commands/services/services/celery_base.py
=> fix: 解决部署后，Oracle无法执行自动化任务问题

apps/accounts/automations/base/manager.py, apps/accounts/automations/change_secret/database/oracle/main.yml
fix: 修复mongodb ssl账号测试失败，oracle推送用户失败问题
=> fix: 修复mongodb ssl账号测试失败，oracle推送用户失败问题

apps/terminal/applets/navicat/app.py
fix: 解决不同用户使用远程应用Navicat登录Oracle失败的问题
=> fix: 解决不同用户使用远程应用Navicat登录Oracle失败的问题

apps/authentication/backends/oauth2/views.py, apps/settings/serializers/auth/oauth2.py
=> fix: 修改OAuth2协议的注销地址为非必填字段

apps/terminal/applets/navicat/app.py, apps/terminal/applets/navicat/const.py
=> perf: 优化applet-navicat连接方式

apps/common/decorators.py
=> fix: 创建Web资产报错

apps/users/api/user.py
=> fix: 用户接口不分页时，api异常

apps/terminal/applets/navicat/app.py
perf: 优化远程应用navicat连接时，确定有密码输入框后才输入密码
=> perf: 优化远程应用navicat连接时，确定有密码输入框后才输入密码

apps/audits/api.py, apps/audits/serializers.py
perf: 优化Activity日志[操作日志、登录日志]显示
=> perf: 优化Activity日志[操作日志、登录日志]显示

apps/terminal/applets/navicat/app.py
fix: 解决applets在razor方式拉起代填错误问题
=> fix: 解决applets在razor方式拉起代填错误问题

apps/terminal/applets/dbeaver/app.py
=> perf: 优化applets-dbeaver依赖驱动方式

apps/accounts/automations/change_secret/database/sqlserver/main.yml
=> fix: 解决SQLServer无法推送用户

apps/assets/serializers/asset/database.py
=> perf: 修改PostgreSQL数据库参数为必填

apps/terminal/applets/dbeaver/manifest.yml
=> perf: 去掉dbeaver的clickhouse协议

apps/jumpserver/rewriting/storage/permissions.py, apps/jumpserver/settings/base.py, apps/jumpserver/urls.py, apps/ops/models/playbook.py, requirements/requirements.txt
=> feat: 增加media权限控制

apps/jumpserver/settings/base.py
=> fix: 远程应用图标无法显示问题

apps/audits/api.py
fix: 解决跨组织资源的Activty在其他组织下404的问题
=> fix: 解决跨组织资源的Activty在其他组织下404的问题

apps/audits/api.py
=> fix: 平台Activity列表500

apps/assets/signal_handlers/asset.py
Fix: 解决资产创建后系统执行Ping及Gather任务失败问题
=> Fix: 解决资产创建后系统执行Ping及Gather任务失败问题

apps/terminal/applets/dbeaver/app.py
Perf: 优化DBeaver连接数据库时，不显示cli-dos窗口
=> Perf: 优化DBeaver连接数据库时，不显示cli-dos窗口

apps/accounts/automations/verify_account/database/mongodb/main.yml, apps/accounts/automations/verify_account/database/oracle/main.yml, apps/accounts/automations/verify_account/database/sqlserver/main.yml
=> fix: 解决部分数据库在修改密码后仍能ping通的问题

apps/audits/api.py, apps/audits/signal_handlers/activity_log.py, apps/orgs/mixins/models.py
=> fix: 操作日志、Activity日志显示当前组织和SYSTEM组织下的内容

apps/audits/backends/db.py, apps/audits/serializers.py, apps/audits/signal_handlers/operate_log.py, apps/audits/utils.py, apps/common/views/mixins.py, apps/settings/serializers/settings.py
=> fix: 操作日志的国际化应该根据查询对象的语言决定

apps/accounts/tasks/verify_account.py, apps/audits/signal_handlers/activity_log.py, apps/common/tasks.py
fix: 创建用户和验证账号任务的Activity日志保存失败
=> fix: 创建用户和验证账号任务的Activity日志保存失败

apps/settings/serializers/auth/base.py, apps/settings/serializers/auth/cas.py, apps/settings/serializers/auth/dingtalk.py, apps/settings/serializers/auth/feishu.py, apps/settings/serializers/auth/ldap.py, apps/settings/serializers/auth/oauth2.py, apps/settings/serializers/auth/oidc.py, apps/settings/serializers/auth/radius.py, apps/settings/serializers/auth/saml2.py, apps/settings/serializers/auth/sso.py, apps/settings/serializers/auth/wecom.py
perf: 修改认证设置类的国际化，字符串方式会直接翻译成国际化内容
=> perf: 修改认证设置类的国际化，字符串方式会直接翻译成国际化内容

apps/assets/automations/base/manager.py
fix: 对于网关无法连接的，给出原因并停止此任务的后续步骤，不影响其他任务
=> fix: 对于网关无法连接的，给出原因并停止此任务的后续步骤，不影响其他任务

README.md
=> perf：更新 README 中的产品 UI 展示截图

apps/accounts/tasks/automation.py, apps/accounts/tasks/backup_account.py, apps/accounts/tasks/gather_accounts.py, apps/accounts/tasks/push_account.py, apps/assets/tasks/automation.py, apps/common/tasks.py, apps/ops/tasks.py, apps/terminal/tasks.py
=> fix: 解决Activity保存因为参数出错问题

apps/audits/utils.py, apps/common/local.py
=> fix: 操作日志显示用户加密后的密文，及日期格式调整

apps/common/local.py
=> fix: 操作日志可能保存明文密码

apps/common/local.py
=> fix: 操作日志有可能保存明文密码

.github/workflows/sync-gitee.yml
Gitee 仓库已经统一到 FIT2CLOUD飞致云组织下，修改目的仓库地址。
将 Gitee 同步任务的目的仓库地址进行了修改。
=> workflow: 修改 Gitee 同步的目的仓库

apps/accounts/api/account/account.py, apps/common/views/mixins.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po
=> perf: 优化账号活动日志界面的提示及操作日志的字段内容

apps/common/validators.py, apps/users/serializers/user.py, requirements/requirements.txt
=> feat: 支持手机号选择区号

apps/common/validators.py, apps/users/serializers/user.py, requirements/requirements.txt
=> feat: 手机号支持选择区号

apps/common/validators.py, apps/users/serializers/user.py
=> fix: 手机号可以为空及验证逻辑修改

apps/common/validators.py
=> fix: 手机号码校验逻辑问题

apps/authentication/models/connection_token.py
perf: 当连接资产为网关时，connection_token不返回网域网关信息
=> perf: 当连接资产为网关时，connection_token不返回网域网关信息

apps/authentication/backends/oauth2/backends.py
perf: 修改OAuth2的access_token前缀格式
=> perf: 修改OAuth2的access_token前缀格式

apps/accounts/automations/change_secret/custom/ssh/manifest.yml, apps/ops/ansible/modules/custom_command.py
perf: 优化自定义改密时需要在命令中包含ssh登录用户的密码问题
=> perf: 优化自定义改密时需要在命令中包含ssh登录用户的密码问题

README.md
=> chore: 更新 README

apps/assets/automations/base/manager.py
perf: 自动化任务执行错误日志在DEBUG_DEV下打印
=> perf: 自动化任务执行错误日志在DEBUG_DEV下打印

apps/authentication/mixins.py
fix: 修复某待审核用户返回时，登录其他用户可绕开mfa的问题
=> fix: 修复某待审核用户返回时，登录其他用户可绕开mfa的问题

apps/audits/handler.py, apps/audits/utils.py
=> perf: 优化命令过滤规则操作日志显示问题

apps/accounts/automations/verify_account/custom/main.yml
fix: 验证账号可连接性(自定义ssh)使用的key值错误
=> fix: 验证账号可连接性(自定义ssh)使用的key值错误

apps/common/sdk/im/wecom/__init__.py
企业微信官方api
https://developer.work.weixin.qq.com/document/path/98151
企业微信扫描登录修改为新版接口，在PC登录企业微信客户端的情况下，不再需要手机扫码。
企业微信扫描登录修改为新版接口
- [ *] Made sure tests are passing and test coverage is added if needed.
- [ *] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ *] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.
=> 企业微信扫描登录修改为新版接口，在PC登录企业微信客户端的情况下，不再需要手机扫码。

apps/tickets/api/ticket.py, apps/tickets/serializers/ticket/ticket.py
fix: 解决具有超级工单权限的用户无法给指定人申请工单问题
=> fix: 解决具有超级工单权限的用户无法给指定人申请工单问题

apps/settings/serializers/auth/cas.py, apps/settings/serializers/auth/ldap.py, apps/settings/serializers/auth/oauth2.py, apps/settings/serializers/auth/oidc.py, apps/settings/serializers/auth/saml2.py, apps/settings/serializers/auth/sms.py
fix: 解决lina不显示json格式参数，优化DictSerializer改为JSONSerialzer
=> fix: 解决lina不显示json格式参数，优化DictSerializer改为JSONSerialzer

requirements/requirements.txt
Reverts jumpserver/jumpserver#10618
=> Revert "chore(deps): bump cryptography from 38.0.4 to 41.0.0 in /requirements"

apps/audits/handler.py, apps/audits/utils.py
=> fix: 资产登录规则操作日志显示优化

apps/terminal/api/session/session.py
=> fix: 解决录像无法在线观看的问题

apps/audits/api.py, apps/audits/tasks.py, apps/terminal/api/session/session.py, apps/terminal/tasks.py
fix: 提供给luna的录像地址不能为本地local地址，应该为url
=> fix: 提供给luna的录像地址不能为本地local地址，应该为url

apps/audits/migrations/0022_auto_20230605_1555.py, apps/audits/models.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po
=> perf: 字段含义和Session model保持一致

apps/accounts/urls.py, apps/common/auth/signature.py
=> fix some typos

apps/notifications/notifications.py
=> perf: 优化飞书接收到的工单审批的连接无法点击的问题

.github/ISSUE_TEMPLATE/----.md
=> feat: Update ----.md

apps/terminal/connect_methods.py
Reverts jumpserver/jumpserver#10893
=> Revert "perf: rdp7 可使用 web gui方式连接"

requirements/requirements_xpack.txt
=> feat: 云同步支持公有云

apps/ops/ansible/inventory.py
=> perf: windows winrm使用ntlm认证

apps/assets/api/mixin.py
=> perf: 修改 sftp 的一些处理

apps/tickets/api/ticket.py
=> feat: 支持批量审批工单

Dockerfile, Dockerfile-ee
Reverts jumpserver/jumpserver#11152
=> Revert "perf: 锁定 Cython==0.29.35 增加 pip 选项 --use-deprecated=legacy-resolver"

poetry.lock
=> perf: 添加清华源

apps/perms/api/user_permission/tree/node_with_asset.py
=> perf: 类型树右击可以获取节点下所有的资产

poetry.lock, pyproject.toml
=> fix: 添加华为云依赖包

Dockerfile
=> perf: Dockerfile中安装nmap工具

apps/audits/signal_handlers/operate_log.py
=> perf: 优化组件的操作行为不记录到操作日志中

apps/audits/signal_handlers/operate_log.py
fix: 操作日志判断is_service_account为匿名用户会报错
=> fix: 操作日志判断is_service_account为匿名用户会报错

apps/settings/tools/ping.py, apps/settings/tools/telnet.py, apps/settings/utils/common.py, apps/settings/ws.py
=> feat: telnet、ping支持批量测试

apps/accounts/api/account/account.py, apps/accounts/api/account/template.py, apps/accounts/mixins.py, apps/audits/const.py, apps/common/api/patch.py, apps/common/views/mixins.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po, apps/terminal/api/session/session.py
=> feat: 查看/下载录像记录在操作及活动日志中

apps/settings/tools/__init__.py, apps/settings/tools/ping.py, apps/settings/tools/traceroute.py, apps/settings/utils/common.py, apps/settings/ws.py
=> feat: 系统工具支持traceroute

apps/accounts/automations/change_secret/database/sqlserver/main.yml, apps/accounts/automations/push_account/database/sqlserver/main.yml
=> fix: 解决sqlserver无法推送和改密的问题

apps/terminal/api/applet/host.py
Reverts jumpserver/jumpserver#11643
=> Revert "perf: 修复 task id 不对的问题"

apps/accounts/serializers/account/account.py, apps/accounts/tasks/push_account.py, apps/common/decorators.py, apps/ops/api/job.py, apps/ops/tasks.py, apps/terminal/api/applet/host.py, apps/terminal/tasks.py
Reverts jumpserver/jumpserver#11642
=> Revert "perf: 修复事务中任务执行"

README.md
=> chore: 优化 README 文案

apps/users/views/profile/reset.py
=> perf: 优化找回密码时区号带加号无法匹配的问题

apps/authentication/mixins.py, apps/common/permissions.py
Reverts jumpserver/jumpserver#11701
=> Revert "fix: pubkey auth require svc sign"

apps/authentication/backends/oidc/views.py, apps/authentication/middleware.py, apps/authentication/mixins.py, apps/locale/ja/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/django.po
=> perf: 优化OIDC用户未激活时，会循环跳转登录页面

apps/settings/utils/ldap.py
=> feat: 支持LDAP用户组变更时，JS同步变更

apps/tickets/templates/tickets/approve_check_password.html, apps/tickets/views/approve.py
=> perf: 工单直接审批者访问链接无认证跳转到登录页面

apps/audits/models.py
=> perf: 使用scan命令扫描在线用户

apps/accounts/automations/backup_account/handlers.py
=> fix: 修改sftp账号备份执行任务的日志提示

apps/authentication/models/access_key.py
Reverts jumpserver/jumpserver#12081
=> Revert "perf: 调整 secret 长度为32位"

apps/assets/const/types.py, apps/jumpserver/middleware.py, apps/jumpserver/settings/base.py
Reverts jumpserver/jumpserver#12078
=> Revert "fix: 修复平台自动化翻译"

apps/authentication/backends/drf.py, apps/common/decorators.py, apps/orgs/signal_handlers/common.py
fix: 延迟执行设置超时
perf: 修改 delay run
perf: 优化 delay_run 执行
perf: 修改 delay run
=> perf: 优化延迟运行

apps/accounts/automations/backup_account/handlers.py, apps/accounts/automations/change_secret/manager.py, poetry.lock, pyproject.toml
=> fix: 账号备份密码如 t08\x08fIE 备份失败

apps/ops/ansible/modules_utils/custom_common.py
Reverts jumpserver/jumpserver#12431
=> Revert "fix: 特定key paramiko 测试可连接性失败"

apps/audits/api.py
Bug] 活动记录 UNION 的类型 character varying 和 uuid 不匹配  #12411
=> fix: UNION 的类型 character varying 和 uuid 不匹配

apps/authentication/backends/oauth2/backends.py
Reverts jumpserver/jumpserver#12597
=> Revert "fix: 修复 OAuth2 认证时 POST 方式获取 access_token API 使用 json 传递数据"

README_EN.md
=> chore: edit readme_en

apps/audits/tasks.py
=> fix: 解决FTP审计文件无法清理的问题

apps/locale/zh/LC_MESSAGES/django.po, apps/locale/zh/LC_MESSAGES/djangojs.po
Reverts jumpserver/jumpserver#12949
=> Revert "feat: 支持中文繁体"

apps/accounts/filters.py
=> fix: 【账号改密】任务列表-详情：获取任务记录tab报错

apps/authentication/api/mfa.py, apps/common/utils/verify_code.py, apps/templates/_mfa_login_field.html
perf: 优化频繁发送短信，将后端的频繁发送警告提示到页面上来提醒用户
=> perf: 优化频繁发送短信，将后端的频繁发送警告提示到页面上来提醒用户

apps/authentication/api/mfa.py, apps/templates/_mfa_login_field.html
=> perf: 优化会话过期500问题

apps/assets/serializers/asset/info/spec.py
=> perf: 优化 Web 资产详情时根据 autofill 类型返回对应的 spec_info 信息

apps/jumpserver/conf.py
change 'jms_receptor' to 'receptor'
=> feat: 修改 receptor 容器通信地址

requirements/requirements.txt
=> fix: redis RLock

apps/authentication/backends/oauth2/views.py
fix: 解决OAuth2可以跳过不存在用户不允许登录的规则
=> fix: 解决OAuth2可以跳过不存在用户不允许登录的规则

.github/workflows/jms-generic-action-handler.yml
=> chrome: change github action

apps/users/templates/users/reset_password.html
创建用户/更新用户，设置 “下次登录须修改密码” 时，用户重置密码界面请求密码为明文，为安全起见，设置为密文传输
=> perf: 登录重置密码传输进行加密

CONTRIBUTING.md
=> chore: use unseq list

apps/authentication/serializers/connection_token.py, apps/i18n/core/en/LC_MESSAGES/django.po, apps/i18n/core/ja/LC_MESSAGES/django.po, apps/i18n/core/zh/LC_MESSAGES/django.po, apps/i18n/core/zh_Hant/LC_MESSAGES/django.po, apps/i18n/lina/en.json, apps/i18n/lina/zh.json, apps/ops/api/job.py, apps/ops/models/job.py, apps/ops/serializers/job.py
=> perf: Translate

README.zh-CN.md
=> chore: Update README.zh-CN.md

apps/authentication/mixins.py
Reverts jumpserver/jumpserver#14695
=> Revert "perf: update const import"

apps/ops/models/job.py
Reverts jumpserver/jumpserver#14798
=> Revert "perf: Optimize average_time_cost calculation in job model"

apps/accounts/migrations/0019_backupaccountautomation_and_more.py, apps/accounts/templates/accounts/backup_account_report.html, apps/accounts/templates/accounts/change_secret_report.html, apps/accounts/templates/accounts/check_account_report.html, apps/accounts/templates/accounts/gather_account_report.html, apps/accounts/templates/accounts/push_account_report.html
Reverts jumpserver/jumpserver#14790
=> Revert "perf: automation report"

apps/settings/serializers/auth/oidc.py
=> fix: OIDC PKCE S256

.github/dependabot.yml
=> chore: Add Dependabot configuration for pip dependencies

apps/common/plugins/es.py, apps/terminal/backends/command/es.py
=> perf:Stored command records in ES support accurate searching.

apps/common/plugins/es.py, apps/terminal/backends/command/es.py
Reverts jumpserver/jumpserver#15242
=> Revert "Revert "perf:Stored command records in ES support accurate searching.""

.github/dependabot.yml
=> chore: use uv as package-ecosystem

.github/dependabot.yml
=> chore: Configure Dependabot to group Python dependencies

apps/common/db/fields.py
Reverts jumpserver/jumpserver#15359
=> Revert "fix: Upgrading django version causes json serialization problems"

README.md, readmes/README.zh-hans.md
=> docs: Add GitCode badges

apps/accounts/utils.py
=> Reformat import statements in utils.py
